version: '3.9'
services:

  mysql:
    image: 'mysql:8'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pigeon
      MYSQL_DATABASE: pigeon
      TZ: Asia/Shanghai
    ports:
      - '3306:3306'

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - mysql

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - mysql
      - backend

volumes:
  mysql-data:
