// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupMsg is the predicate function for groupmsg builders.
type GroupMsg func(*sql.Selector)

// PrivateMsg is the predicate function for privatemsg builders.
type PrivateMsg func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
