// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keepcalmx/go-pigeon/ent/groupmsg"
	"github.com/keepcalmx/go-pigeon/ent/predicate"
)

// GroupMsgQuery is the builder for querying GroupMsg entities.
type GroupMsgQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.GroupMsg
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroupMsgQuery builder.
func (gmq *GroupMsgQuery) Where(ps ...predicate.GroupMsg) *GroupMsgQuery {
	gmq.predicates = append(gmq.predicates, ps...)
	return gmq
}

// Limit adds a limit step to the query.
func (gmq *GroupMsgQuery) Limit(limit int) *GroupMsgQuery {
	gmq.limit = &limit
	return gmq
}

// Offset adds an offset step to the query.
func (gmq *GroupMsgQuery) Offset(offset int) *GroupMsgQuery {
	gmq.offset = &offset
	return gmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gmq *GroupMsgQuery) Unique(unique bool) *GroupMsgQuery {
	gmq.unique = &unique
	return gmq
}

// Order adds an order step to the query.
func (gmq *GroupMsgQuery) Order(o ...OrderFunc) *GroupMsgQuery {
	gmq.order = append(gmq.order, o...)
	return gmq
}

// First returns the first GroupMsg entity from the query.
// Returns a *NotFoundError when no GroupMsg was found.
func (gmq *GroupMsgQuery) First(ctx context.Context) (*GroupMsg, error) {
	nodes, err := gmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{groupmsg.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gmq *GroupMsgQuery) FirstX(ctx context.Context) *GroupMsg {
	node, err := gmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GroupMsg ID from the query.
// Returns a *NotFoundError when no GroupMsg ID was found.
func (gmq *GroupMsgQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{groupmsg.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gmq *GroupMsgQuery) FirstIDX(ctx context.Context) int {
	id, err := gmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GroupMsg entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GroupMsg entity is found.
// Returns a *NotFoundError when no GroupMsg entities are found.
func (gmq *GroupMsgQuery) Only(ctx context.Context) (*GroupMsg, error) {
	nodes, err := gmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{groupmsg.Label}
	default:
		return nil, &NotSingularError{groupmsg.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gmq *GroupMsgQuery) OnlyX(ctx context.Context) *GroupMsg {
	node, err := gmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GroupMsg ID in the query.
// Returns a *NotSingularError when more than one GroupMsg ID is found.
// Returns a *NotFoundError when no entities are found.
func (gmq *GroupMsgQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{groupmsg.Label}
	default:
		err = &NotSingularError{groupmsg.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gmq *GroupMsgQuery) OnlyIDX(ctx context.Context) int {
	id, err := gmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GroupMsgs.
func (gmq *GroupMsgQuery) All(ctx context.Context) ([]*GroupMsg, error) {
	if err := gmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gmq *GroupMsgQuery) AllX(ctx context.Context) []*GroupMsg {
	nodes, err := gmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GroupMsg IDs.
func (gmq *GroupMsgQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := gmq.Select(groupmsg.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gmq *GroupMsgQuery) IDsX(ctx context.Context) []int {
	ids, err := gmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gmq *GroupMsgQuery) Count(ctx context.Context) (int, error) {
	if err := gmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gmq *GroupMsgQuery) CountX(ctx context.Context) int {
	count, err := gmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gmq *GroupMsgQuery) Exist(ctx context.Context) (bool, error) {
	if err := gmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gmq *GroupMsgQuery) ExistX(ctx context.Context) bool {
	exist, err := gmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroupMsgQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gmq *GroupMsgQuery) Clone() *GroupMsgQuery {
	if gmq == nil {
		return nil
	}
	return &GroupMsgQuery{
		config:     gmq.config,
		limit:      gmq.limit,
		offset:     gmq.offset,
		order:      append([]OrderFunc{}, gmq.order...),
		predicates: append([]predicate.GroupMsg{}, gmq.predicates...),
		// clone intermediate query.
		sql:    gmq.sql.Clone(),
		path:   gmq.path,
		unique: gmq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		From string `json:"from,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroupMsg.Query().
//		GroupBy(groupmsg.FieldFrom).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gmq *GroupMsgQuery) GroupBy(field string, fields ...string) *GroupMsgGroupBy {
	grbuild := &GroupMsgGroupBy{config: gmq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gmq.sqlQuery(ctx), nil
	}
	grbuild.label = groupmsg.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		From string `json:"from,omitempty"`
//	}
//
//	client.GroupMsg.Query().
//		Select(groupmsg.FieldFrom).
//		Scan(ctx, &v)
func (gmq *GroupMsgQuery) Select(fields ...string) *GroupMsgSelect {
	gmq.fields = append(gmq.fields, fields...)
	selbuild := &GroupMsgSelect{GroupMsgQuery: gmq}
	selbuild.label = groupmsg.Label
	selbuild.flds, selbuild.scan = &gmq.fields, selbuild.Scan
	return selbuild
}

func (gmq *GroupMsgQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gmq.fields {
		if !groupmsg.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gmq.path != nil {
		prev, err := gmq.path(ctx)
		if err != nil {
			return err
		}
		gmq.sql = prev
	}
	return nil
}

func (gmq *GroupMsgQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GroupMsg, error) {
	var (
		nodes = []*GroupMsg{}
		_spec = gmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GroupMsg).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GroupMsg{config: gmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (gmq *GroupMsgQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gmq.querySpec()
	_spec.Node.Columns = gmq.fields
	if len(gmq.fields) > 0 {
		_spec.Unique = gmq.unique != nil && *gmq.unique
	}
	return sqlgraph.CountNodes(ctx, gmq.driver, _spec)
}

func (gmq *GroupMsgQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := gmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (gmq *GroupMsgQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   groupmsg.Table,
			Columns: groupmsg.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groupmsg.FieldID,
			},
		},
		From:   gmq.sql,
		Unique: true,
	}
	if unique := gmq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gmq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupmsg.FieldID)
		for i := range fields {
			if fields[i] != groupmsg.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gmq *GroupMsgQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gmq.driver.Dialect())
	t1 := builder.Table(groupmsg.Table)
	columns := gmq.fields
	if len(columns) == 0 {
		columns = groupmsg.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gmq.sql != nil {
		selector = gmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gmq.unique != nil && *gmq.unique {
		selector.Distinct()
	}
	for _, p := range gmq.predicates {
		p(selector)
	}
	for _, p := range gmq.order {
		p(selector)
	}
	if offset := gmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GroupMsgGroupBy is the group-by builder for GroupMsg entities.
type GroupMsgGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gmgb *GroupMsgGroupBy) Aggregate(fns ...AggregateFunc) *GroupMsgGroupBy {
	gmgb.fns = append(gmgb.fns, fns...)
	return gmgb
}

// Scan applies the group-by query and scans the result into the given value.
func (gmgb *GroupMsgGroupBy) Scan(ctx context.Context, v any) error {
	query, err := gmgb.path(ctx)
	if err != nil {
		return err
	}
	gmgb.sql = query
	return gmgb.sqlScan(ctx, v)
}

func (gmgb *GroupMsgGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range gmgb.fields {
		if !groupmsg.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := gmgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gmgb *GroupMsgGroupBy) sqlQuery() *sql.Selector {
	selector := gmgb.sql.Select()
	aggregation := make([]string, 0, len(gmgb.fns))
	for _, fn := range gmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(gmgb.fields)+len(gmgb.fns))
		for _, f := range gmgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(gmgb.fields...)...)
}

// GroupMsgSelect is the builder for selecting fields of GroupMsg entities.
type GroupMsgSelect struct {
	*GroupMsgQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (gms *GroupMsgSelect) Scan(ctx context.Context, v any) error {
	if err := gms.prepareQuery(ctx); err != nil {
		return err
	}
	gms.sql = gms.GroupMsgQuery.sqlQuery(ctx)
	return gms.sqlScan(ctx, v)
}

func (gms *GroupMsgSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := gms.sql.Query()
	if err := gms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
