// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keepcalmx/go-pigeon/ent/groupmsg"
)

// GroupMsgCreate is the builder for creating a GroupMsg entity.
type GroupMsgCreate struct {
	config
	mutation *GroupMsgMutation
	hooks    []Hook
}

// SetFrom sets the "from" field.
func (gmc *GroupMsgCreate) SetFrom(s string) *GroupMsgCreate {
	gmc.mutation.SetFrom(s)
	return gmc
}

// SetTo sets the "to" field.
func (gmc *GroupMsgCreate) SetTo(s string) *GroupMsgCreate {
	gmc.mutation.SetTo(s)
	return gmc
}

// SetType sets the "type" field.
func (gmc *GroupMsgCreate) SetType(s string) *GroupMsgCreate {
	gmc.mutation.SetType(s)
	return gmc
}

// SetContent sets the "content" field.
func (gmc *GroupMsgCreate) SetContent(s string) *GroupMsgCreate {
	gmc.mutation.SetContent(s)
	return gmc
}

// SetCreatedAt sets the "created_at" field.
func (gmc *GroupMsgCreate) SetCreatedAt(t time.Time) *GroupMsgCreate {
	gmc.mutation.SetCreatedAt(t)
	return gmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (gmc *GroupMsgCreate) SetNillableCreatedAt(t *time.Time) *GroupMsgCreate {
	if t != nil {
		gmc.SetCreatedAt(*t)
	}
	return gmc
}

// Mutation returns the GroupMsgMutation object of the builder.
func (gmc *GroupMsgCreate) Mutation() *GroupMsgMutation {
	return gmc.mutation
}

// Save creates the GroupMsg in the database.
func (gmc *GroupMsgCreate) Save(ctx context.Context) (*GroupMsg, error) {
	var (
		err  error
		node *GroupMsg
	)
	gmc.defaults()
	if len(gmc.hooks) == 0 {
		if err = gmc.check(); err != nil {
			return nil, err
		}
		node, err = gmc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GroupMsgMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = gmc.check(); err != nil {
				return nil, err
			}
			gmc.mutation = mutation
			if node, err = gmc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(gmc.hooks) - 1; i >= 0; i-- {
			if gmc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = gmc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, gmc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*GroupMsg)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from GroupMsgMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (gmc *GroupMsgCreate) SaveX(ctx context.Context) *GroupMsg {
	v, err := gmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gmc *GroupMsgCreate) Exec(ctx context.Context) error {
	_, err := gmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gmc *GroupMsgCreate) ExecX(ctx context.Context) {
	if err := gmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gmc *GroupMsgCreate) defaults() {
	if _, ok := gmc.mutation.CreatedAt(); !ok {
		v := groupmsg.DefaultCreatedAt
		gmc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (gmc *GroupMsgCreate) check() error {
	if _, ok := gmc.mutation.From(); !ok {
		return &ValidationError{Name: "from", err: errors.New(`ent: missing required field "GroupMsg.from"`)}
	}
	if _, ok := gmc.mutation.To(); !ok {
		return &ValidationError{Name: "to", err: errors.New(`ent: missing required field "GroupMsg.to"`)}
	}
	if _, ok := gmc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "GroupMsg.type"`)}
	}
	if _, ok := gmc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "GroupMsg.content"`)}
	}
	if _, ok := gmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GroupMsg.created_at"`)}
	}
	return nil
}

func (gmc *GroupMsgCreate) sqlSave(ctx context.Context) (*GroupMsg, error) {
	_node, _spec := gmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (gmc *GroupMsgCreate) createSpec() (*GroupMsg, *sqlgraph.CreateSpec) {
	var (
		_node = &GroupMsg{config: gmc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: groupmsg.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: groupmsg.FieldID,
			},
		}
	)
	if value, ok := gmc.mutation.From(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groupmsg.FieldFrom,
		})
		_node.From = value
	}
	if value, ok := gmc.mutation.To(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groupmsg.FieldTo,
		})
		_node.To = value
	}
	if value, ok := gmc.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groupmsg.FieldType,
		})
		_node.Type = value
	}
	if value, ok := gmc.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: groupmsg.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := gmc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: groupmsg.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	return _node, _spec
}

// GroupMsgCreateBulk is the builder for creating many GroupMsg entities in bulk.
type GroupMsgCreateBulk struct {
	config
	builders []*GroupMsgCreate
}

// Save creates the GroupMsg entities in the database.
func (gmcb *GroupMsgCreateBulk) Save(ctx context.Context) ([]*GroupMsg, error) {
	specs := make([]*sqlgraph.CreateSpec, len(gmcb.builders))
	nodes := make([]*GroupMsg, len(gmcb.builders))
	mutators := make([]Mutator, len(gmcb.builders))
	for i := range gmcb.builders {
		func(i int, root context.Context) {
			builder := gmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GroupMsgMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gmcb *GroupMsgCreateBulk) SaveX(ctx context.Context) []*GroupMsg {
	v, err := gmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gmcb *GroupMsgCreateBulk) Exec(ctx context.Context) error {
	_, err := gmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gmcb *GroupMsgCreateBulk) ExecX(ctx context.Context) {
	if err := gmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
