// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/keepcalmx/go-pigeon/ent/predicate"
	"github.com/keepcalmx/go-pigeon/ent/privatemsg"
)

// PrivateMsgDelete is the builder for deleting a PrivateMsg entity.
type PrivateMsgDelete struct {
	config
	hooks    []Hook
	mutation *PrivateMsgMutation
}

// Where appends a list predicates to the PrivateMsgDelete builder.
func (pmd *PrivateMsgDelete) Where(ps ...predicate.PrivateMsg) *PrivateMsgDelete {
	pmd.mutation.Where(ps...)
	return pmd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pmd *PrivateMsgDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(pmd.hooks) == 0 {
		affected, err = pmd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PrivateMsgMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pmd.mutation = mutation
			affected, err = pmd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(pmd.hooks) - 1; i >= 0; i-- {
			if pmd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pmd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pmd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (pmd *PrivateMsgDelete) ExecX(ctx context.Context) int {
	n, err := pmd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pmd *PrivateMsgDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: privatemsg.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: privatemsg.FieldID,
			},
		},
	}
	if ps := pmd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pmd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// PrivateMsgDeleteOne is the builder for deleting a single PrivateMsg entity.
type PrivateMsgDeleteOne struct {
	pmd *PrivateMsgDelete
}

// Exec executes the deletion query.
func (pmdo *PrivateMsgDeleteOne) Exec(ctx context.Context) error {
	n, err := pmdo.pmd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{privatemsg.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pmdo *PrivateMsgDeleteOne) ExecX(ctx context.Context) {
	pmdo.pmd.ExecX(ctx)
}
