// Code generated by ent, DO NOT EDIT.

package privatemsg

import (
	"time"
)

const (
	// Label holds the string label denoting the privatemsg type in the database.
	Label = "private_msg"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFrom holds the string denoting the from field in the database.
	FieldFrom = "from"
	// FieldTo holds the string denoting the to field in the database.
	FieldTo = "to"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldRead holds the string denoting the read field in the database.
	FieldRead = "read"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the privatemsg in the database.
	Table = "private_msgs"
)

// Columns holds all SQL columns for privatemsg fields.
var Columns = []string{
	FieldID,
	FieldFrom,
	FieldTo,
	FieldType,
	FieldContent,
	FieldRead,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt time.Time
)
