package constant

const (
	SYSTEM_GROUP_UUID               = "99bfc045093640429e24cebcfac5b5c7"
	DEFAULT_MSG_LIMIT               = 100
	DEFAULT_PRIVATE_MSG_CACHE_LIMIT = 1000
	DEFAULT_GROUP_MSG_CACHE_LIMIT   = 10000
)

// sizes
const (
	SMALL_BUFFER_SIZE = 1024
	MID_BUFFER_SIZE   = SMALL_BUFFER_SIZE << 2
	LARGE_BUFFER_SIZE = MID_BUFFER_SIZE << 4
)

// types
const (
	MESSAGE_TYPE = "message"
	STATUS_TYPE  = "status"
)
